shared:
  ioc-instance:
    # Pandablocks IOC image
    image: ghcr.io/pandablocks/pandablocks-ioc:0.11.5
    # this places the start.sh directly in the epics/ioc folder replacing where
    # the framework usually looks for the global start.sh
    iocConfig: /epics/ioc

    # use p38detector account ID and group ID for access to /dls/p38/data
    securityContext:
      runAsUser: 37143
      runAsGroup: 37143

    dataVolume:
      # don't create a pvc - instead we will mount a host folder
      pvc: false
      # A path on the host machine to write data into. Also used as the path where
      # the folder will be mounted inside of the container so that users need not
      # be confused about inside/outside container paths.
      hostPath: /dls/p38/data
